### ISSUE TITLE
give me the credit 💀💀💀

### ISSUE THREAD

**Issue by 7gh** [Geekeh/BloxFlip-discord-predictor#1]
maybe think about giving the fucking original owner credit?? that guy didnt make it LOL, also u didnt do shit to this fucking skid

**Comment by Geekeh** [comment]
Don't see it on ur github nor did i know u existed lmfao, also it didn't work when i found it and now it does that doesn't magically happen

**Comment by 7gh** [comment]
> Don't see it on ur github nor did i know u existed lmfao, also it didn't work when i found it and now it does that doesn't magically happen. If you are refering to this https://github.com/7gh/bloxflip-predictor it has been taken down by someone meaning you are not the orignial owner. ![image](https://user-images.githubusercontent.com/98252854/187088367-7489dbd2-7a0d-4a99-b7e0-d83098dc072e.png)

uh it actually got dmca'd by fucking ice bear retard u can go to it and itll say dmca

**Comment by 7gh** [comment]
i think

**Comment by Geekeh** [comment]
No, It doesn't. But I can't give credit to someone who doesn't even have the repo anywhere public

**Comment by hibdusne** [comment]
Was wondering lol

**Comment by TheonlyIcebear** [comment]
Both of you shut the fuck up ALL OF THE CODE IS FROM ME, except for the retarded parts, you clearly cannot code please uninstall python. Also the equation your using is from over a fucking year ago 💀, complete dog shit
