### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by TheonlyIcebear** [Geekeh/BloxFlip-discord-predictor#6]
You're using a equation from me that's from like over a year ago, not only that but you even used fucking samples of my code, also please learn pep8 you skid 💀. You code like you're a toddler who just found a computer and accidentally installed python after smearing his shit all over the screen

**Comment by Geekeh** [comment]
Never claimed i made it, "fixed someones src so it works now". it was sum random code i found in a discord. i could also care less about pep 8
